### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by nemanjazajk** [PatrickRose/bootstrapper-docs#6]

**Comment by PatrickRose** [comment]
Hi @nemanjazajk  - I see you've removed the question but in case someone stumbles across this again:

```
{!! Button::danger(trans("Invoice signiture"))->withAttributes(array('id' => 'saveButton', 'onclick' => 'onSaveClick()')) !!}
```

This is equivalent to writing `<button class="btn btn-danger" id="saveButton" onclick="onSaveClick()">Invoice signiture</button>` in your template. Bootstrapper just helps add the various classes for you so you don't have to.

The `onSaveClick()` is a JS function - you'll need to make sure that's included somewhere on the page the button is displayed on.
